project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "MBG4421 Bioinformatics"
  navbar:
    left:
      - href: index.qmd
        text: Ana Sayfa
      - href: about.qmd
        text: Hakkında
format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
