# MBG4421 Biyoinformatik

- Ders notları bu sayfada paylaşılacaktır. Ders notlarımız Türkçe olacktır fakat takip edilen site (Galaxy Training) İngilizce dilindedir. Gerektiğinde tarayıcınızın çeviri özelliğini kullanıp içerikleri Türkçe'ye çevirebilirsiniz.
- Uygulamaları gerçekleştirmek için, öğrencilerin Galaxy ortamında hesap açması gerekmektedir. Halka açık bir çok Galaxy sunucu bulunmaktadır, yoğunluk veya içerik açısından farklar olabileceğinden usegalaxy.org , usegalaxy.eu ve usegalaxy.org.au sitelerinde hesap açmanız yararlı olacaktır.

## Ders1

*1 Ekim 2024 Salı* tarihinde Galaxy sitesi tanıtıldı 

## Ders2 

*8 Ekim 2024 Salı* tarihinde Galaxy kullanımını gösteren üç örnek yapılacaktır. [Sunum linki](ders2.qmd)

## Ders3

*15 Ekim 2024 Salı* tarihinde Docking (Yanaştırma) konusu işlenecektir. [Sunum linki](ders3.qmd)

## Ders4 

*22 Ekim 2024 Salı* tarihinde NGS (yeni nesil dizileme) verileri konusuna giriş yapılacaktır. [Sunum linki](ders4.qmd)

## Ders5

*5 Kasım 2024 Salı* tarihinde "RNA-Seq reads to counts" ve "RNA-Seq from counts to genes" adlı materyaller işlenmiştir. [Sunum linki](ders5.qmd)

## Ders6

*12 Kasım 2024 Salı* tarihinde Ders5 sonundaki Workflow yapıldı [Sunum linki](ders5.qmd)

## Ders7

*26 Kasım 2024 Salı* tarihinde "genes to pathways" isimli uygulama yapılmıştur. [Sunum linki](ders7.qmd)

## Ders8

*3 Aralık 2024 Salı* tarihinde "variant calling" konusu işlendi. [Sunum linki](ders8.qmd)

## Ders9

*10 Aralık 2024 Salı* tarihinde "ATAC-Seq" konusu işlendi. [Sunum linki](ders9.qmd)

## Ders10

*17 Aralık 2024 Salı* tarihinde "Metagenomik" konusu işlendi. [Sunum linki](ders10.qmd)

